import type { WorkspaceData } from '../domain/types';
import { Icon } from '../components/Icon';
import { PageHeader, StatusBadge } from '../components/ui';

export function CompanyPage({ workspace }: { workspace: WorkspaceData }) {
  return (
    <div className="page">
      <PageHeader eyebrow="Workspace master" title="Company setup" description="Legal identity, reporting framework, period, materiality, users and local-storage controls." actions={<button className="button button-primary"><Icon name="settings" size={16}/> Edit setup</button>}/>
      <section className="setup-grid">
        <article className="panel setup-card setup-company"><div className="setup-card-heading"><span className="card-icon"><Icon name="company"/></span><StatusBadge tone="green">ACTIVE</StatusBadge></div><h2>{workspace.company.legalName}</h2><p>{workspace.company.registeredOffice}</p><dl><div><dt>CIN</dt><dd>{workspace.company.cin}</dd></div><div><dt>Industry</dt><dd>{workspace.company.industry}</dd></div><div><dt>Currency</dt><dd>Indian rupees (INR)</dd></div><div><dt>Presentation scale</dt><dd>{workspace.company.displayScale.toLowerCase()}</dd></div></dl></article>
        <article className="panel setup-card"><div className="setup-card-heading"><span className="card-icon"><Icon name="statements"/></span><StatusBadge tone="blue">DIVISION I</StatusBadge></div><h2>Reporting framework</h2><p>Schedule III Division I-oriented presentation for a standalone non-Ind AS commercial/industrial company.</p><dl><div><dt>Taxonomy</dt><dd>{workspace.period.taxonomyVersion}</dd></div><div><dt>Validation rules</dt><dd>{workspace.period.rulesetVersion}</dd></div><div><dt>Materiality</dt><dd>₹2.50 lakh</dd></div><div><dt>Consolidation</dt><dd>Not enabled</dd></div></dl></article>
        <article className="panel setup-card"><div className="setup-card-heading"><span className="card-icon"><Icon name="review"/></span><StatusBadge tone="amber">{workspace.period.status.replaceAll('_', ' ')}</StatusBadge></div><h2>{workspace.period.label}</h2><p>{new Date(`${workspace.period.startDate}T00:00:00`).toLocaleDateString('en-IN')} — {new Date(`${workspace.period.endDate}T00:00:00`).toLocaleDateString('en-IN')}</p><dl><div><dt>Comparative</dt><dd>{workspace.period.comparativeLabel}</dd></div><div><dt>Revision</dt><dd>{workspace.period.revision}</dd></div><div><dt>Active TB</dt><dd>{workspace.activeImport.fileName}</dd></div><div><dt>Imported rows</dt><dd>{workspace.activeImport.rowCount}</dd></div></dl></article>
      </section>
      <section className="panel users-panel"><div className="panel-heading"><div><span className="panel-kicker">Least-privilege roles</span><h2>Local users & review segregation</h2></div><button className="button button-secondary"><Icon name="plus" size={15}/> Add local user</button></div><div className="user-list">{workspace.users.map((user) => <div key={user.id}><span className="user-avatar">{user.displayName.split(' ').map((part) => part[0]).join('').slice(0,2)}</span><div><strong>{user.displayName}</strong><small>@{user.username}</small></div><StatusBadge tone={user.role === 'REVIEWER' ? 'blue' : user.role === 'ADMIN' ? 'neutral' : 'green'}>{user.role}</StatusBadge><span className="positive">Active</span><button className="icon-button"><Icon name="more"/></button></div>)}</div></section>
      <section className="setup-security-grid"><article className="panel"><Icon name="database"/><div><h3>Browser-local database</h3><p>All company and financial records live in this browser profile under IndexedDB. Nothing is synchronised automatically.</p></div></article><article className="panel"><Icon name="wifi-off"/><div><h3>Offline ready</h3><p>After installation, the application shell and local data remain available without an Internet connection.</p></div></article><article className="panel"><Icon name="shield"/><div><h3>Recovery responsibility</h3><p>Browser storage is not an archive. Download encrypted backups after material work and before finalisation.</p></div></article></section>
    </div>
  );
}
